violations:
  pep8: pep8 . --exclude='*migrations*,*settings*,*components*,*docs*'
  sloccount: sloccount .
  py_unittest: cat test_out
  coverage: coverage report
  pip_review:
    command: pip-review
    nofail: true
