language: python
python:
  - "3.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
install:
  - npm install -g bower
  - cp deploy_trigger/settings/local_ci.py deploy_trigger/settings/local.py
  - pip install -r requirements/ci.txt
script:
  - coverage run manage.py test tasks 2>test_out
after_script:
  - coverage report
  - coveralls
  - covio
